Traceback (most recent call last):
  File "deep_tf.py", line 138, in <module>
    main()
  File "deep_tf.py", line 81, in main
    model = return_model(model_arch, max_len, vocab_size)
  File "/home/u9773662/hpcai/2022-APAC-HPC-AI/Deep_Learning_Based_DNA_Sequence_Fast_Decoding/models.py", line 50, in return_model
    'swin': swin(max_len, vocab_size)
  File "/home/u9773662/hpcai/2022-APAC-HPC-AI/Deep_Learning_Based_DNA_Sequence_Fast_Decoding/models.py", line 36, in swin
    model = Sequential([
  File "/home/u9773662/.local/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/u9773662/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/u9773662/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: Exception encountered when calling layer "swin_tiny_224" (type SwinTransformerModel).

in user code:

    File "/home/u9773662/hpcai/2022-APAC-HPC-AI/Deep_Learning_Based_DNA_Sequence_Fast_Decoding/swintransformer/model.py", line 422, in call  *
        x = self.forward_features(x)
    File "/home/u9773662/hpcai/2022-APAC-HPC-AI/Deep_Learning_Based_DNA_Sequence_Fast_Decoding/swintransformer/model.py", line 411, in forward_features  *
        x = self.patch_embed(x)
    File "/home/u9773662/.local/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None

    ValueError: Exception encountered when calling layer "patch_embed" (type PatchEmbed).
    
    in user code:
    
        File "/home/u9773662/hpcai/2022-APAC-HPC-AI/Deep_Learning_Based_DNA_Sequence_Fast_Decoding/swintransformer/model.py", line 335, in call  *
            B, H, W, C = x.get_shape().as_list()
    
        ValueError: not enough values to unpack (expected 4, got 3)
    
    
    Call arguments received:
      • x=tf.Tensor(shape=(None, 10240, 5), dtype=float32)


Call arguments received:
  • x=tf.Tensor(shape=(None, 10240, 5), dtype=float32)
srun: error: gn1227: task 3: Exited with exit code 1